import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

  // Team 1 sidebar
  abcSidebar: [{type: 'autogenerated', dirName: 'abc'}],

  // Team 2 sidebar
  defSidebar: [{type: 'autogenerated', dirName: 'def'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['abc/create-a-document'],
    },
  ],
   */
};

export default sidebars;
